apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
  namespace: default
data:
  db-hostname: mongo
  db-username: devdb
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-password
  namespace: default
type: Opaque
data:
  db-password: ZGV2ZGJAMTIz
